/* eslint-disable no-useless-escape */
// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver');
const assert = require('assert');
const {describe, beforeEach, afterEach, it} = require('mocha');
const SeleniumDriver = require('../drivers/slenium');

describe('mic toggle', function() {
  this.timeout(0);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = new SeleniumDriver();
    vars = {};
  });

  it('mic toggle', async function() {
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[4]/button/img[2]")).click();
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[4]/button")).click();
  });
});
