/* eslint-disable no-useless-escape */
// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver');
const assert = require('assert');
const {describe, beforeEach, afterEach, it} = require('mocha');
const SeleniumDriver = require('../drivers/slenium');

describe('room', function() {
  this.timeout(0);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = new SeleniumDriver();
    vars = {};
  });

  it('room', async function() {
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[3]/button/img")).click();
    {
      const element = await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[3]/button/img"));
      await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform();
    }
    {
      const element = await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[3]/button"));
      await driver.actions({bridge: true}).moveToElement(element).release().perform();
    }
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header/div/div/div/div[3]/button")).click();
  });
});
