/* eslint-disable no-useless-escape */
// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver');
const assert = require('assert');
const {describe, beforeEach, afterEach, it} = require('mocha');
const SeleniumDriver = require('../drivers/slenium');

describe('World tokens', function() {
  this.timeout(0);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = new SeleniumDriver();
    vars = {};
  });
  it('World tokens', async function() {
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header[2]/div/div[2]/div/span[2]")).click();
    await driver.findElement(By.xpath("//div[@id=\'app\']/div/div[5]/header[2]/div/div[2]/div/span")).click();
  });
});
