
export const ActionTypes = {
  InitializeState: 'InitializeState',
  InitializeStateEnd: 'InitializeStateEnd',
  MintNft: 'MintNft',
  SendNft: 'SendNft',
  BuyNft: 'BuyNft',
  SellNft: 'SellNft',
  DestroyNft: 'DestroyNft',
  AddFtToNft: 'AddFtToNft',
  DepositFt: 'DepositFt',
  WithdrawFt: 'WithdrawFt',
  ConnectMainnetWallet: 'ConnectMainnetWallet',
  GetProfileForCreator: 'GetProfileForCreator',
  GetProfileForCreatorEnd: 'GetProfileForCreatorEnd',
  GetInventoryForCreator: 'GetInventoryForCreator',
  GetBooths: 'GetBooths',
  GetCreators: 'GetCreators',
  CopyAddress: 'CopyAddress',
  CopyPrivateKey: 'CopyPrivateKey',
  ChangeName: 'ChangeName',
  SetAvatar: 'SetAvatar',
  SetHomespace: 'SetHomespace',
  AddToLoadout: 'AddToLoadout',
  RemoveFromLoadout: 'RemoveFromLoadout',
  UploadFile: 'UploadFile',
  AddToLoadout: 'SetFtu',
  AddToLoadout: 'AddToLoadout',
  AddToLoadout: 'AddToLoadout',
  AddToLoadout: 'AddToLoadout',
  LoginWithEmailOrPrivateKey: 'LoginWithEmailOrPrivateKey',
  RequestEmailToken: 'RequestEmailToken',
  GatewayWithEmail: 'LoginWithEmail',
  Logout: 'Logout'
};

export default ActionTypes;