
export const ActionTypes = {
  InitializeState: 'InitializeState',
  InitializeStateEnd: 'InitializeStateEnd',
  MintNft: 'MintNft',
  SendNft: 'SendNft',
  BuyNft: 'BuyNft',
  SellNft: 'SellNft',
  UnsellNft: 'UnsellNft',
  DestroyNft: 'DestroyNft',
  AddFtToNft: 'AddFtToNft',
  DepositFt: 'DepositFt',
  WithdrawFt: 'WithdrawFt',
  DepositNft: 'DepositNft',
  WithdrawNft: 'WithdrawNft',
  ConnectMainnetWallet: 'ConnectMainnetWallet',
  DisonnectMainnetWallet: 'DisonnectMainnetWallet',
  GetBoothForCreator: 'GetBoothForCreator',
  GetProfileForCreator: 'GetProfileForCreator',
  GetInventoryForCreator: 'GetInventoryForCreator',
  ReturnAsyncState: 'ReturnAsyncState',
  GetBooths: 'GetBooths',
  GetCreators: 'GetCreators',
  CopyAddress: 'CopyAddress',
  CopyPrivateKey: 'CopyPrivateKey',
  AddToLoadout: 'AddToLoadout',
  RemoveFromLoadout: 'RemoveFromLoadout',
  UploadFile: 'UploadFile',
  AddToLoadout: 'SetFtu',
  AddToLoadout: 'AddToLoadout',
  AddToLoadout: 'AddToLoadout',
  AddToLoadout: 'AddToLoadout',
  LoginWithEmailOrPrivateKey: 'LoginWithEmailOrPrivateKey',
  RequestEmailToken: 'RequestEmailToken',
  GatewayWithEmail: 'LoginWithEmail',
  Logout: 'Logout'
};

export default ActionTypes;