export const InitialStateValues = {
  useWebXR: false,
  loginToken: null,
  name: null,
  mainnetAddress: null,
  mainnetFtBalance: null,
  mainnetInventory: null,
  showUserDropdown: false,
  address: null,
  avatarUrl: null,
  avatarFileName: null,
  avatarPreview: null,
  homespaceUrl: null,
  homespaceFileName: null,
  homespacePreview: null,
  ftu: true,
  inventory: null,
  creatorProfiles: {},
  creatorInventories: {},
  creatorBooths: {},
  creators: {},
  booths: {},
  loadouts: {},
  lastFileHash: null,
  lastFileId: null
};
